/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";

import { motion } from "framer-motion";
import Link from "next/link";
import { ArrowLeft, ExternalLink, Code, TrendingUp, Sparkles, Building2, Layers } from "lucide-react";
import Image from "next/image";

type Project = {
  id: string;
  title: string;
  slug: string;
  content: string;
  description: string;
  image: string;
  cardImage?: string | null;
  bannerImage?: string | null;
  client: string | null;
  tags: string;
  serviceCategory?: string;
  beforeStats?: string;
  afterStats?: string;
  beforeImage?: string | null;
  afterImage?: string | null;
  growthBadge?: string;
  challenge?: string;
  solution?: string;
  liveUrl: string | null;
  githubUrl: string | null;
  videoUrl?: string | null;
  galleryImages?: string[];
  socialMediaStats?: any[];
  featured: boolean;
  createdAt: Date;
  updatedAt: Date;
  metaTitle?: string | null;
  metaDescription?: string | null;
  imageAltText?: string | null;
};

const fadeIn = {
  initial: { opacity: 0, y: 20 },
  animate: { opacity: 1, y: 0 },
  transition: { duration: 0.7, ease: "easeOut" }
};

const staggerContainer = {
  animate: {
    transition: {
      staggerChildren: 0.15
    }
  }
};

// Markdown & HTML Helper for Case Studies
function parseMarkdown(md: string): string {
  if (!md) return "";
  
  // If already HTML content generated by Quill Editor, return directly
  if (md.includes("<p>") || md.includes("<h1>") || md.includes("<h2>") || md.includes("<h3>") || md.includes("<h4>") || md.includes("<div") || md.includes("<ul>")) {
    return md;
  }


  let html = md;

  // Headings
  html = html.replace(/^### (.*$)/gim, '<h3 class="text-xl md:text-2xl font-black text-[#ffbe00] mt-8 mb-4 border-b border-white/10 pb-2 flex items-center gap-2"><span class="w-2 h-2 rounded-full bg-[#ffbe00]"></span><span>$1</span></h3>');
  html = html.replace(/^## (.*$)/gim, '<h2 class="text-2xl md:text-3xl font-black text-[#ffbe00] mt-10 mb-6 border-b border-[#ffbe00]/20 pb-3 tracking-tight">$1</h2>');
  html = html.replace(/^# (.*$)/gim, '<h1 class="text-3xl md:text-4xl font-black text-[#ffbe00] mt-10 mb-6">$1</h1>');


  // Bold & Italic
  html = html.replace(/\*\*(.*?)\*\*/g, '<strong class="font-black text-white">$1</strong>');
  html = html.replace(/\*(.*?)\*/g, '<em class="italic text-amber-200">$1</em>');

  // Bullet Lists & Numbered Lists (Markdown format)
  html = html.replace(/^[\*\-•] (.*$)/gim, '<li class="flex items-start gap-3 my-2 text-gray-200 font-medium text-sm md:text-base"><span class="text-[#ffbe00] font-black text-lg leading-none">•</span><span>$1</span></li>');
  html = html.replace(/^(\d+)\. (.*$)/gim, '<li class="flex items-start gap-3 my-2 text-gray-200 font-medium text-sm md:text-base"><span class="text-[#ffbe00] font-extrabold text-sm px-2 py-0.5 rounded-md bg-[#ffbe00]/10 border border-[#ffbe00]/30">$1</span><span>$2</span></li>');

  // Wrap consecutive Markdown <li> into <ul> if not already wrapped
  html = html.replace(/(<li class="flex items-start.*<\/li>\n?)+/g, '<ul class="my-6 p-6 md:p-8 rounded-3xl bg-black/40 border border-white/10 space-y-2 shadow-inner">$1</ul>');

  // Paragraphs for plain markdown text blocks
  if (!html.includes("<p>") && !html.includes("<div") && !html.includes("<ul")) {
    const blocks = html.split(/\n\n+/);
    html = blocks.map(block => {
      const trimmed = block.trim();
      if (!trimmed) return "";
      if (trimmed.startsWith("<h") || trimmed.startsWith("<ul") || trimmed.startsWith("<li") || trimmed.startsWith("<div")) {
        return trimmed;
      }
      return `<p class="text-base md:text-lg text-[#dcd7e3] leading-relaxed mb-6 font-medium">${trimmed}</p>`;
    }).join("\n");
  }

  return html;
}



import { useState } from "react";
import { useRouter } from "next/navigation";

export function PortfolioContent({ project }: { project: Project }) {
  const router = useRouter();
  const [activePlatform, setActivePlatform] = useState<string>(project?.socialMediaStats?.[0]?.platform || "");
  const tags = (project.tags || "").split(",").map((tag: string) => tag.trim()).filter(Boolean);
  const beforeLines = (project.beforeStats || "").split("\n").filter(Boolean);
  const afterLines = (project.afterStats || "").split("\n").filter(Boolean);

  return (
    <article className="pb-24 bg-mesh relative overflow-hidden">
      {/* Ambient Gradients */}
      <div className="absolute top-0 right-1/4 w-[600px] h-[600px] bg-[#ffbe00]/10 rounded-full blur-[150px] pointer-events-none" />
      <div className="absolute bottom-1/4 left-1/4 w-[600px] h-[600px] bg-[#24182e]/10 rounded-full blur-[150px] pointer-events-none" />

      <div className="max-w-6xl mx-auto px-6 lg:px-8 relative z-10 pt-28">
        
        {/* Navigation */}
        <motion.div initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: 0.5 }}>
          <button 
            type="button"
            onClick={() => {
              if (typeof window !== "undefined" && window.history.length > 1) {
                router.back();
              } else {
                router.push("/portfolio");
              }
            }}
            className="inline-flex items-center gap-2 text-muted uppercase tracking-widest text-xs font-bold group mb-8 hover:text-[#ffbe00] transition-colors cursor-pointer"
          >
            <ArrowLeft size={16} className="transition-transform group-hover:-translate-x-1" />
            Back to Case Studies & Portfolio
          </button>
        </motion.div>

        {/* Hero Header */}
        <motion.header 
          variants={staggerContainer}
          initial="initial"
          animate="animate"
          className="mb-12 flex flex-col"
        >
          <motion.div variants={fadeIn} className="flex flex-wrap items-center gap-3 mb-4">
            {project.serviceCategory && (
              <span className="px-4 py-1.5 bg-[#ffbe00] text-[#24182e] rounded-full text-xs font-black uppercase tracking-[0.15em] shadow-md flex items-center gap-1.5">
                <Layers size={13} /> {project.serviceCategory.replace("-", " ")}
              </span>
            )}
            {project.growthBadge && (
              <span className="px-4 py-1.5 bg-emerald-500 text-[#090512] font-black text-xs uppercase tracking-wider rounded-full shadow-md flex items-center gap-1.5">
                <TrendingUp size={14} /> {project.growthBadge}
              </span>
            )}
            {tags.map((tag, idx) => (
              <span key={idx} className="px-3.5 py-1 bg-white/10 text-foreground rounded-full text-xs font-bold uppercase tracking-wider border border-white/15">
                {tag}
              </span>
            ))}
          </motion.div>
          
          <motion.h1 variants={fadeIn} className="text-4xl md:text-6xl font-black text-foreground tracking-tight leading-[1.08] mb-6 max-w-5xl">
            {project.title}
          </motion.h1>
          
          <motion.div variants={fadeIn} className="flex flex-wrap items-center justify-between gap-6 text-sm font-medium border-y border-card-border py-6 bg-card/20 backdrop-blur-sm px-8 rounded-3xl">
            {project.client && (
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-full bg-[#ffbe00]/20 flex items-center justify-center text-[#ffbe00]">
                  <Building2 size={20} />
                </div>
                <div>
                  <span className="block text-xs font-bold uppercase tracking-widest text-muted">Client / Company</span>
                  <span className="text-xl font-black text-foreground">{project.client}</span>
                </div>
              </div>
            )}
            
            <div className="flex flex-wrap gap-4">
              {project.liveUrl && (
                <a href={project.liveUrl} target="_blank" rel="noopener noreferrer" className="flex items-center gap-2 text-[#24182e] hover:text-[#ffbe00] transition-colors bg-[#ffbe00] hover:bg-[#24182e] hover:text-white px-6 py-3 rounded-2xl shadow-lg font-black tracking-wide text-xs uppercase group">
                  <ExternalLink size={16} className="group-hover:scale-110 transition-transform" />
                  <span>Visit Live Website</span>
                </a>
              )}
              {project.githubUrl && (
                <a href={project.githubUrl} target="_blank" rel="noopener noreferrer" className="flex items-center gap-2 text-white bg-[#24182e] hover:bg-[#ffbe00] hover:text-[#24182e] transition-colors px-6 py-3 rounded-2xl shadow-md font-black tracking-wide text-xs uppercase group">
                  <Code size={16} className="group-hover:scale-110 transition-transform" />
                  <span>Tech Repository</span>
                </a>
              )}
            </div>
          </motion.div>
        </motion.header>

        {/* Cover Feature Image */}
        {project.videoUrl ? (
          <motion.div 
            initial={{ opacity: 0, y: 40 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.2 }}
            className="w-full relative rounded-[2.5rem] overflow-hidden shadow-2xl border border-card-border mb-16 aspect-video group"
          >
            <iframe 
              src={project.videoUrl.replace("watch?v=", "embed/").replace("vimeo.com/", "player.vimeo.com/video/")}
              title={project.title}
              className="absolute inset-0 w-full h-full border-0"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
              allowFullScreen
            />
          </motion.div>
        ) : (
          <motion.div 
            initial={{ opacity: 0, y: 40 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.2 }}
            className="w-full relative rounded-[2.5rem] overflow-hidden shadow-2xl border border-white/10 mb-16 group flex items-center justify-center"
          >
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img 
              src={project.bannerImage || project.image} 
              alt={project.imageAltText || project.title}
              className="w-full h-auto max-h-[750px] object-contain rounded-[2.5rem] transition-transform duration-700 group-hover:scale-[1.01]"
            />
          </motion.div>
        )}



        {project.galleryImages && project.galleryImages.length > 0 && (
          <motion.div 
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.7 }}
            className="grid grid-cols-2 md:grid-cols-3 gap-6 mb-16 max-w-5xl mx-auto"
          >
            {project.galleryImages.map((img, idx) => (
              <div key={idx} className="relative aspect-square md:aspect-[4/3] rounded-3xl overflow-hidden shadow-lg border border-white/10 group">
                <Image src={img} alt={`Gallery ${idx + 1}`} fill className="object-cover group-hover:scale-110 transition-transform duration-700" />
              </div>
            ))}
          </motion.div>
        )}

        <div className="max-w-5xl mx-auto space-y-16 mb-24">
          
          {/* BEFORE VS AFTER IMPACT COMPARISON CARD */}
          {(project.beforeStats || project.afterStats || project.beforeImage || project.afterImage) && (
            <motion.div 
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.7 }}
              className="p-8 md:p-12 bg-gradient-to-br from-[#24182e] via-[#1a1122] to-[#120b18] rounded-[2.5rem] border border-white/15 shadow-2xl text-white relative overflow-hidden"
            >
              <div className="flex items-center gap-3 mb-8">
                <div className="w-12 h-12 rounded-2xl bg-[#ffbe00]/20 flex items-center justify-center text-[#ffbe00]">
                  <Sparkles size={24} />
                </div>
                <div>
                  <h3 className="text-2xl font-black uppercase tracking-tight text-white">Before vs After Performance Results</h3>
                  <p className="text-xs text-[#dcd7e3]/70">Verified ROI metrics before and after working with Aeronox Solutions.</p>
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                {/* BEFORE */}
                <div className="bg-red-500/10 border border-red-500/30 p-6 md:p-8 rounded-3xl relative overflow-hidden flex flex-col justify-between">
                  <div>
                    <div className="flex items-center gap-2 text-red-400 font-black uppercase tracking-wider text-xs mb-4">
                      <span className="w-3 h-3 rounded-full bg-red-500 animate-pulse" /> 🛑 Before Aeronox Solutions
                    </div>
                    {beforeLines.length > 0 && (
                      <ul className="space-y-3 text-sm text-gray-200 font-medium mb-4">
                        {beforeLines.map((line: string, idx: number) => {
                          const cleanText = line.replace(/^[•\-\*\s]+/, "").trim();
                          if (!cleanText) return null;
                          return (
                            <li key={idx} className="flex items-start gap-2">
                              <span className="text-red-400 font-bold">•</span>
                              <span>{cleanText}</span>
                            </li>
                          );
                        })}
                      </ul>
                    )}
                  </div>
                  {project.beforeImage && (
                    <div className="relative h-48 w-full rounded-2xl overflow-hidden border border-red-500/30 mt-4 shadow-lg">
                      <Image src={project.beforeImage} alt="Before Aeronox State" fill className="object-cover" />
                      <span className="absolute bottom-2 right-2 bg-black/80 text-red-400 text-xs px-2.5 py-1 rounded-lg font-black uppercase">Before State</span>
                    </div>
                  )}
                </div>

                {/* AFTER */}
                <div className="bg-emerald-500/10 border border-emerald-500/30 p-6 md:p-8 rounded-3xl relative overflow-hidden shadow-lg flex flex-col justify-between">
                  <div>
                    <div className="flex items-center justify-between gap-2 text-emerald-400 font-black uppercase tracking-wider text-xs mb-4">
                      <span className="flex items-center gap-2">
                        <span className="w-3 h-3 rounded-full bg-emerald-500 animate-pulse" /> 🚀 After Aeronox (Results)
                      </span>
                      {project.growthBadge && (
                        <span className="px-3 py-1 bg-emerald-500 text-black font-black text-[10px] rounded-full uppercase">
                          {project.growthBadge}
                        </span>
                      )}
                    </div>
                    {afterLines.length > 0 && (
                      <ul className="space-y-3 text-sm text-emerald-100 font-bold mb-4">
                        {afterLines.map((line: string, idx: number) => {
                          const cleanText = line.replace(/^[•\-\*\s]+/, "").trim();
                          if (!cleanText) return null;
                          return (
                            <li key={idx} className="flex items-start gap-2">
                              <span className="text-emerald-400 font-black">✓</span>
                              <span>{cleanText}</span>
                            </li>
                          );
                        })}
                      </ul>
                    )}
                  </div>
                  {project.afterImage && (
                    <div className="relative h-48 w-full rounded-2xl overflow-hidden border border-emerald-500/30 mt-4 shadow-lg">
                      <Image src={project.afterImage} alt="After Aeronox Results" fill className="object-cover" />
                      <span className="absolute bottom-2 right-2 bg-emerald-500 text-black text-xs px-2.5 py-1 rounded-lg font-black uppercase">Delivered Result</span>
                    </div>
                  )}
                </div>
              </div>
            </motion.div>
          )}

          {/* SOCIAL MEDIA STATS */}
          {project.socialMediaStats && project.socialMediaStats.length > 0 && (
            <motion.div 
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.7 }}
              className="p-8 md:p-12 bg-[#1a1122] rounded-[2.5rem] border border-white/10 shadow-2xl relative overflow-hidden"
            >
              <div className="flex items-center gap-3 mb-8">
                <div className="w-12 h-12 rounded-2xl bg-[#ff3b30]/20 flex items-center justify-center text-[#ff3b30]">
                  <TrendingUp size={24} />
                </div>
                <div>
                  <h3 className="text-2xl font-black uppercase tracking-tight text-white">Social Media Campaign Stats</h3>
                  <p className="text-xs text-[#dcd7e3]/70">Platform-specific growth and engagement metrics.</p>
                </div>
              </div>

              {/* Platform Tabs */}
              <div className="flex flex-wrap gap-3 mb-8">
                {project.socialMediaStats.map((stat, idx) => (
                  <button
                    key={idx}
                    onClick={() => setActivePlatform(stat.platform)}
                    className={`px-6 py-3 rounded-xl font-bold uppercase tracking-wider text-sm transition-all ${
                      activePlatform === stat.platform 
                        ? "bg-[#ff3b30] text-white shadow-[0_0_20px_rgba(255,59,48,0.4)]" 
                        : "bg-white/5 text-white/70 hover:bg-white/10"
                    }`}
                  >
                    {stat.platform}
                  </button>
                ))}
              </div>

              {/* Active Platform Content */}
              {project.socialMediaStats.filter(s => s.platform === activePlatform).map((stat, idx) => (
                <div key={idx} className="space-y-8 animate-in fade-in zoom-in-95 duration-300">
                  {stat.description && (
                    <div className="bg-white/5 border border-white/10 p-6 rounded-2xl text-[#dcd7e3] text-sm md:text-base leading-relaxed">
                      {stat.description}
                    </div>
                  )}
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                    <div className="bg-red-500/10 border border-red-500/30 p-6 md:p-8 rounded-3xl relative flex flex-col justify-between">
                      <div>
                        <div className="text-red-400 font-black uppercase tracking-wider text-xs mb-4 flex items-center gap-2">
                          <span className="w-3 h-3 rounded-full bg-red-500 animate-pulse" /> Before Campaign
                        </div>
                        <div className="whitespace-pre-line text-sm text-red-100/90 font-medium leading-relaxed">
                          {stat.beforeStats || "N/A"}
                        </div>
                      </div>
                      {stat.beforeImage && (
                        <div className="relative h-40 md:h-48 w-full rounded-2xl overflow-hidden border border-red-500/30 mt-6 shadow-lg">
                          <Image src={stat.beforeImage} alt={`${stat.platform} Before`} fill className="object-cover" />
                        </div>
                      )}
                    </div>
                    <div className="bg-emerald-500/10 border border-emerald-500/30 p-6 md:p-8 rounded-3xl relative flex flex-col justify-between">
                      <div>
                        <div className="text-emerald-400 font-black uppercase tracking-wider text-xs mb-4 flex items-center gap-2">
                          <span className="w-3 h-3 rounded-full bg-emerald-500 animate-pulse" /> After Campaign
                        </div>
                        <div className="whitespace-pre-line text-sm text-emerald-100/90 font-bold leading-relaxed">
                          {stat.afterStats || "N/A"}
                        </div>
                      </div>
                      {stat.afterImage && (
                        <div className="relative h-40 md:h-48 w-full rounded-2xl overflow-hidden border border-emerald-500/30 mt-6 shadow-lg">
                          <Image src={stat.afterImage} alt={`${stat.platform} After`} fill className="object-cover" />
                        </div>
                      )}
                    </div>
                  </div>
                </div>
              ))}
            </motion.div>
          )}

          {/* CHALLENGE VS SOLUTION CARDS */}
          {(project.challenge || project.solution) && (
            <motion.div 
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.7 }}
              className="grid grid-cols-1 md:grid-cols-2 gap-8"
            >
              {project.challenge && (
                <div className="p-8 bg-gradient-to-br from-[#24182e] via-[#1a1122] to-[#140c1e] text-white rounded-[2rem] border border-amber-500/30 shadow-2xl relative overflow-hidden">
                  <div className="absolute top-0 right-0 w-32 h-32 bg-amber-500/10 rounded-full blur-2xl pointer-events-none" />
                  <h4 className="text-xl font-black text-amber-400 uppercase tracking-tight mb-3 flex items-center gap-2 relative z-10">
                    <span className="text-amber-400">⚠️</span> The Challenge
                  </h4>
                  <p className="text-gray-200 leading-relaxed text-sm md:text-base font-medium relative z-10">
                    {project.challenge}
                  </p>
                </div>
              )}

              {project.solution && (
                <div className="p-8 bg-gradient-to-br from-[#24182e] via-[#1a1122] to-[#120b18] text-white rounded-[2rem] border border-[#ffbe00]/30 shadow-2xl relative overflow-hidden">
                  <div className="absolute top-0 right-0 w-32 h-32 bg-[#ffbe00]/10 rounded-full blur-2xl pointer-events-none" />
                  <h4 className="text-xl font-black text-[#ffbe00] uppercase tracking-tight mb-3 flex items-center gap-2 relative z-10">
                    <span>💡</span> The Strategy & Solution
                  </h4>
                  <p className="text-[#dcd7e3]/95 leading-relaxed text-sm md:text-base font-medium relative z-10">
                    {project.solution}
                  </p>
                </div>
              )}
            </motion.div>
          )}

          {/* DETAILED CONTENT */}
          {project.content && (
            <motion.div 
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.7 }}
            >
              <div className="bg-gradient-to-br from-[#24182e] via-[#1d1326] to-[#140c1e] text-white p-8 md:p-14 rounded-[2.5rem] border border-white/15 shadow-2xl relative overflow-hidden">
                <div className="absolute top-0 left-0 w-full h-2 bg-gradient-to-r from-[#ffbe00] to-[#24182e]" />
                
                <div 
                  className="max-w-none text-[#dcd7e3] space-y-4 break-words overflow-hidden rich-content"
                  dangerouslySetInnerHTML={{ __html: parseMarkdown(project.content) }}
                />

              </div>
            </motion.div>
          )}

        </div>

        {/* CTA BANNER */}
        <motion.div 
          initial={{ opacity: 0, y: 40 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.7 }}
          className="pt-16 border-t border-card-border"
        >
          <div className="bg-gradient-to-br from-[#24182e] via-[#1a1122] to-[#120b18] p-12 md:p-20 rounded-[3rem] border border-white/15 text-center shadow-2xl relative overflow-hidden group">
            <div className="absolute top-0 right-0 w-64 h-64 bg-[#ffbe00]/20 rounded-full blur-[80px] opacity-0 group-hover:opacity-100 transition-opacity duration-700 pointer-events-none transform translate-x-1/2 -translate-y-1/2" />
            <div className="absolute bottom-0 left-0 w-64 h-64 bg-[#ffbe00]/10 rounded-full blur-[80px] opacity-0 group-hover:opacity-100 transition-opacity duration-700 pointer-events-none transform -translate-x-1/2 translate-y-1/2" />
            
            <h3 className="font-display text-3xl md:text-5xl font-extrabold text-white mb-6 tracking-tight relative z-10">
              Ready to scale your business with similar results?
            </h3>
            <p className="text-base md:text-xl text-gray-300 mb-10 max-w-2xl mx-auto leading-relaxed relative z-10">
              Partner with Aeronox Solutions to engineer custom software, high-converting web applications, or scalable organic acquisition channels.
            </p>
            <Link 
              href="/contact" 
              className="inline-flex items-center justify-center px-10 py-5 bg-[#ffbe00] text-[#24182e] font-black uppercase tracking-[0.1em] rounded-full hover:bg-white hover:scale-105 transition-all duration-300 shadow-[0_0_20px_rgba(255,190,0,0.3)] relative z-10"
            >
              Start Your Project Today
            </Link>
          </div>
        </motion.div>
      </div>
    </article>
  );
}
